#!/bin/sh
# I used sdkman.io to install the spring cli used below.
# 1) curl -s "https://get.sdkman.io" | bash
# 2) sdk install springboot
spring init --dependencies=actuator,actuator-docs,data-jpa,data-rest,data-rest-hal,devtools,flyway,h2,jdbc,jersey,restdocs,thymeleaf,web 
jar xf demo.zip
rm mvnw mvnw.cmd 
rm demo.zip
cat >> .gitignore <<EOF
.mvn/
target
EOF
# Since things will not work unless there is at least one flyway migration
cat > src/main/resources/db/migration/V1__init.sql <<EOF
CREATE TABLE PERSON (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(255) not null,
	last_name varchar(255) not null
);

create sequence person_sequence start with 1 increment by 1;

insert into PERSON (first_name, last_name) values ('James', 'Gosling');
EOF
cat <<EOF
Please try these things?
1. mvn spring-boot:run
2. Visit http://localhost:8080
3. Visit http://localhost:8080
EOF